package com.subspaceparasite.handler;

import com.subspaceparasite.SubspaceParasite;
import com.subspaceparasite.common.entity.base.EntityParasiteBase;
import com.subspaceparasite.common.entity.monster.abomination.EntityAbominationAmalgam;
import com.subspaceparasite.common.entity.monster.abomination.EntityAbominationChimera;
import com.subspaceparasite.common.entity.monster.abomination.EntityAbominationHydra;
import com.subspaceparasite.common.entity.monster.adapted.EntityBanoAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityCanraAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityColonyAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityCreeperAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityEmanaAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityEndermanAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityGimAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityHullAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityIkiAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityLumAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityNoglaAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityRanracAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityShycoAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntitySkeletonAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntitySpiderAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityWymoAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityZaaAdapted;
import com.subspaceparasite.common.entity.monster.adapted.EntityZombieAdapted;
import com.subspaceparasite.common.entity.monster.ancient.EntityAncientColossus;
import com.subspaceparasite.common.entity.monster.ancient.EntityAncientDreadnought;
import com.subspaceparasite.common.entity.monster.ancient.EntityAncientLeviathan;
import com.subspaceparasite.common.entity.monster.assimilated.EntityAssimilatedCow;
import com.subspaceparasite.common.entity.monster.assimilated.EntityAssimilatedHuman;
import com.subspaceparasite.common.entity.monster.assimilated.EntityAssimilatedSheep;
import com.subspaceparasite.common.entity.monster.beckon.EntityBeckonCommon;
import com.subspaceparasite.common.entity.monster.beckon.EntityBeckonEpic;
import com.subspaceparasite.common.entity.monster.beckon.EntityBeckonLegendary;
import com.subspaceparasite.common.entity.monster.beckon.EntityBeckonRare;
import com.subspaceparasite.common.entity.monster.beckon.EntityBeckonUncommon;
import com.subspaceparasite.common.entity.monster.crude.EntityCruxA;
import com.subspaceparasite.common.entity.monster.crude.EntityCruxB;
import com.subspaceparasite.common.entity.monster.crude.EntityDone;
import com.subspaceparasite.common.entity.monster.crude.EntityEgas;
import com.subspaceparasite.common.entity.monster.crude.EntityHeed;
import com.subspaceparasite.common.entity.monster.crude.EntityHost;
import com.subspaceparasite.common.entity.monster.crude.EntityInhooM;
import com.subspaceparasite.common.entity.monster.crude.EntityInhooS;
import com.subspaceparasite.common.entity.monster.crude.EntityLeer;
// Note: crude.EntityLesh conflicts with inborn.EntityLesh - using FQN where needed
import com.subspaceparasite.common.entity.monster.crude.EntityMes;
import com.subspaceparasite.common.entity.monster.crude.EntityMindim;
import com.subspaceparasite.common.entity.monster.crude.EntityMovingFlesh;
import com.subspaceparasite.common.entity.monster.crude.EntityQuac;
import com.subspaceparasite.common.entity.monster.crude.EntityScorcher;
import com.subspaceparasite.common.entity.monster.crude.EntityWorker;
import com.subspaceparasite.common.entity.monster.derived.EntityDerivedCrawler;
import com.subspaceparasite.common.entity.monster.derived.EntityDerivedFly;
import com.subspaceparasite.common.entity.monster.derived.EntityDerivedLeaper;
import com.subspaceparasite.common.entity.monster.derived.EntityDerivedStalker;
import com.subspaceparasite.common.entity.monster.derived.EntityDerivedSwarm;
import com.subspaceparasite.common.entity.monster.derived.EntityHeblu;
import com.subspaceparasite.common.entity.monster.derived.EntityKirin;
import com.subspaceparasite.common.entity.monster.deterrent.EntityDeterrentBastion;
import com.subspaceparasite.common.entity.monster.deterrent.EntityDeterrentOutpost;
import com.subspaceparasite.common.entity.monster.deterrent.EntityDeterrentSentry;
import com.subspaceparasite.common.entity.monster.deterrent.EntityVenkrolSIV;
import com.subspaceparasite.common.entity.monster.dispatcher.EntityDispatcherCommon;
import com.subspaceparasite.common.entity.monster.dispatcher.EntityDispatcherEpic;
import com.subspaceparasite.common.entity.monster.dispatcher.EntityDispatcherRare;
import com.subspaceparasite.common.entity.monster.dispatcher.EntityDispatcherUncommon;
import com.subspaceparasite.common.entity.monster.dispatcher.EntityDodT;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralCow;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralCreeper;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralEnderman;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralHuman;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralIronGolem;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralSkeleton;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralSpider;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralWolf;
import com.subspaceparasite.common.entity.monster.feral.EntityFeralZombie;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedCreeper;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedEnderman;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedEvoker;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedPillager;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedRavager;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedSkeleton;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedSpider;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedWitch;
import com.subspaceparasite.common.entity.monster.hijacked.EntityHijackedZombie;
import com.subspaceparasite.common.entity.monster.inborn.EntityAlafin;
import com.subspaceparasite.common.entity.monster.inborn.EntityAta;
import com.subspaceparasite.common.entity.monster.inborn.EntityButhol;
import com.subspaceparasite.common.entity.monster.inborn.EntityCanal;
import com.subspaceparasite.common.entity.monster.inborn.EntityGothol;
import com.subspaceparasite.common.entity.monster.inborn.EntityKol;
import com.subspaceparasite.common.entity.monster.inborn.EntityLesh;
import com.subspaceparasite.common.entity.monster.inborn.EntityLodo;
import com.subspaceparasite.common.entity.monster.inborn.EntityMor;
import com.subspaceparasite.common.entity.monster.inborn.EntityMudo;
import com.subspaceparasite.common.entity.monster.inborn.EntityNormas;
import com.subspaceparasite.common.entity.monster.inborn.EntityNuuh;
import com.subspaceparasite.common.entity.monster.inborn.EntityObus;
import com.subspaceparasite.common.entity.monster.inborn.EntityRathol;
import com.subspaceparasite.common.entity.monster.inborn.EntityViin;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedBat;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedBee;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedBlaze;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedCaveSpider;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedChicken;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedCow;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedCreeper;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedDrowned;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedEnderman;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedEvoker;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedFox;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedGhast;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedHorse;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedHuman;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedHusk;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedIronGolem;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedLlama;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedMooshroom;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedPanda;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedPhantom;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedPig;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedPillager;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedPolarBear;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedRavager;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedSheep;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedSkeleton;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedSnowGolem;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedSpider;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedStray;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedVillager;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedWarden;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedWitch;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedWitherSkeleton;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedWolf;
import com.subspaceparasite.common.entity.monster.infected.EntityInfectedZombie;
import com.subspaceparasite.common.entity.monster.misc.EntityAlveoliWorm;
import com.subspaceparasite.common.entity.monster.misc.EntityBoomOrb;
import com.subspaceparasite.common.entity.monster.misc.EntityBuglin;
import com.subspaceparasite.common.entity.monster.misc.EntityParasiteLarva;
import com.subspaceparasite.common.entity.monster.misc.EntityVoidOrb;
import com.subspaceparasite.common.entity.monster.nexus.EntityNak;
import com.subspaceparasite.common.entity.monster.nexus.EntityTonro;
import com.subspaceparasite.common.entity.monster.nexus.EntityUnvo;
import com.subspaceparasite.common.entity.monster.preeminent.EntityPreeminentMarauder;
import com.subspaceparasite.common.entity.monster.preeminent.EntityPreeminentSovereign;
import com.subspaceparasite.common.entity.monster.preeminent.EntityPreeminentWarden;
import com.subspaceparasite.common.entity.monster.primitive.EntityArachnida;
import com.subspaceparasite.common.entity.monster.primitive.EntityBano;
import com.subspaceparasite.common.entity.monster.primitive.EntityBolster;
import com.subspaceparasite.common.entity.monster.primitive.EntityBomph;
import com.subspaceparasite.common.entity.monster.primitive.EntityBurrower;
import com.subspaceparasite.common.entity.monster.primitive.EntityCanra;
import com.subspaceparasite.common.entity.monster.primitive.EntityDevourer;
import com.subspaceparasite.common.entity.monster.primitive.EntityEmana;
import com.subspaceparasite.common.entity.monster.primitive.EntityGim;
import com.subspaceparasite.common.entity.monster.primitive.EntityHull;
import com.subspaceparasite.common.entity.monster.primitive.EntityIki;
import com.subspaceparasite.common.entity.monster.primitive.EntityLongarms;
import com.subspaceparasite.common.entity.monster.primitive.EntityLum;
import com.subspaceparasite.common.entity.monster.primitive.EntityManducater;
import com.subspaceparasite.common.entity.monster.primitive.EntityNogla;
import com.subspaceparasite.common.entity.monster.primitive.EntityPrimitiveWolf;
import com.subspaceparasite.common.entity.monster.primitive.EntityRanrac;
import com.subspaceparasite.common.entity.monster.primitive.EntityReeker;
import com.subspaceparasite.common.entity.monster.primitive.EntityShyco;
import com.subspaceparasite.common.entity.monster.primitive.EntitySummoner;
import com.subspaceparasite.common.entity.monster.primitive.EntityTozon;
import com.subspaceparasite.common.entity.monster.primitive.EntityVermin;
import com.subspaceparasite.common.entity.monster.primitive.EntityViscera;
import com.subspaceparasite.common.entity.monster.primitive.EntityWymo;
import com.subspaceparasite.common.entity.monster.primitive.EntityYelloweye;
import com.subspaceparasite.common.entity.monster.primitive.EntityZaa;
import com.subspaceparasite.common.entity.monster.projectile.EntityAcidSpit;
import com.subspaceparasite.common.entity.monster.projectile.EntityBeckonBlast;
import com.subspaceparasite.common.entity.monster.projectile.EntityBileBomb;
import com.subspaceparasite.common.entity.monster.projectile.EntityNexusBeam;
import com.subspaceparasite.common.entity.monster.projectile.EntityParasiteWeb;
import com.subspaceparasite.common.entity.monster.projectile.EntitySporeCloud;
import com.subspaceparasite.common.entity.monster.projectile.EntityVirulentShot;
import com.subspaceparasite.common.entity.monster.pure.EntityAlafha;
import com.subspaceparasite.common.entity.monster.pure.EntityAnged;
import com.subspaceparasite.common.entity.monster.pure.EntityCreeperPure;
import com.subspaceparasite.common.entity.monster.pure.EntityElvia;
import com.subspaceparasite.common.entity.monster.pure.EntityEndermanPure;
import com.subspaceparasite.common.entity.monster.pure.EntityEsor;
import com.subspaceparasite.common.entity.monster.pure.EntityFlam;
import com.subspaceparasite.common.entity.monster.pure.EntityFlog;
import com.subspaceparasite.common.entity.monster.pure.EntityGanro;
import com.subspaceparasite.common.entity.monster.pure.EntityOmboo;
import com.subspaceparasite.common.entity.monster.pure.EntitySkeletonPure;
import com.subspaceparasite.common.entity.monster.pure.EntitySpiderPure;
import com.subspaceparasite.common.entity.monster.pure.EntityWolfPure;
import com.subspaceparasite.common.entity.monster.pure.EntityZombiePure;
import com.subspaceparasite.common.entity.monster.rooter.EntityLeemB;
import com.subspaceparasite.common.entity.monster.rooter.EntityRooterCommon;
import com.subspaceparasite.common.entity.monster.rooter.EntityRooterEpic;
import com.subspaceparasite.common.entity.monster.rooter.EntityRooterRare;
import com.subspaceparasite.common.entity.monster.rooter.EntityRooterUncommon;
import com.subspaceparasite.core.ModEntities;
import net.minecraft.world.entity.SpawnPlacements;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.event.entity.EntityAttributeModificationEvent;
import net.minecraftforge.event.entity.SpawnPlacementRegisterEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Mod event handler registered to the modEventBus.
 * Handles entity registration events including attribute creation,
 * attribute modification, and spawn placement registration.
 * <p>
 * All parasite entity types now have specific implementations
 * with dedicated attribute suppliers.
 */
@Mod.EventBusSubscriber(modid = SubspaceParasite.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModEventHandler {

    private static final Logger LOGGER = LogManager.getLogger();

    /**
     * Register attributes for ALL parasite entity types.
     * Each entity type has its own createAttributes() method
     * that returns tier-appropriate base stats with entity-specific overrides.
     */
    @SubscribeEvent
    public static void onEntityAttributeCreation(EntityAttributeCreationEvent event) {
        event.put(ModEntities.INFECTED_HUMAN.get(), EntityInfectedHuman.createAttributes().build());
        event.put(ModEntities.INFECTED_COW.get(), EntityInfectedCow.createAttributes().build());
        event.put(ModEntities.INFECTED_SHEEP.get(), EntityInfectedSheep.createAttributes().build());
        event.put(ModEntities.INFECTED_CREEPER.get(), EntityInfectedCreeper.createAttributes().build());
        event.put(ModEntities.INFECTED_SKELETON.get(), EntityInfectedSkeleton.createAttributes().build());
        event.put(ModEntities.INFECTED_ZOMBIE.get(), EntityInfectedZombie.createAttributes().build());
        event.put(ModEntities.INFECTED_SPIDER.get(), EntityInfectedSpider.createAttributes().build());
        event.put(ModEntities.INFECTED_ENDERMAN.get(), EntityInfectedEnderman.createAttributes().build());
        event.put(ModEntities.INFECTED_PIG.get(), EntityInfectedPig.createAttributes().build());
        event.put(ModEntities.INFECTED_CHICKEN.get(), EntityInfectedChicken.createAttributes().build());
        event.put(ModEntities.INFECTED_VILLAGER.get(), EntityInfectedVillager.createAttributes().build());
        event.put(ModEntities.INFECTED_WOLF.get(), EntityInfectedWolf.createAttributes().build());
        event.put(ModEntities.INFECTED_HORSE.get(), EntityInfectedHorse.createAttributes().build());
        event.put(ModEntities.INFECTED_IRON_GOLEM.get(), EntityInfectedIronGolem.createAttributes().build());
        event.put(ModEntities.INFECTED_SNOW_GOLEM.get(), EntityInfectedSnowGolem.createAttributes().build());
        event.put(ModEntities.INFECTED_BAT.get(), EntityInfectedBat.createAttributes().build());
        event.put(ModEntities.INFECTED_BLAZE.get(), EntityInfectedBlaze.createAttributes().build());
        event.put(ModEntities.INFECTED_WITCH.get(), EntityInfectedWitch.createAttributes().build());
        event.put(ModEntities.INFECTED_RAVAGER.get(), EntityInfectedRavager.createAttributes().build());
        event.put(ModEntities.INFECTED_PILLAGER.get(), EntityInfectedPillager.createAttributes().build());
        event.put(ModEntities.INFECTED_EVOKER.get(), EntityInfectedEvoker.createAttributes().build());
        event.put(ModEntities.INFECTED_GHAST.get(), EntityInfectedGhast.createAttributes().build());
        event.put(ModEntities.INFECTED_PHANTOM.get(), EntityInfectedPhantom.createAttributes().build());
        event.put(ModEntities.INFECTED_WARDEN.get(), EntityInfectedWarden.createAttributes().build());
        event.put(ModEntities.INFECTED_WITHER_SKELETON.get(), EntityInfectedWitherSkeleton.createAttributes().build());
        event.put(ModEntities.INFECTED_STRAY.get(), EntityInfectedStray.createAttributes().build());
        event.put(ModEntities.INFECTED_HUSK.get(), EntityInfectedHusk.createAttributes().build());
        event.put(ModEntities.INFECTED_DROWNED.get(), EntityInfectedDrowned.createAttributes().build());
        event.put(ModEntities.INFECTED_CAVE_SPIDER.get(), EntityInfectedCaveSpider.createAttributes().build());
        event.put(ModEntities.INFECTED_MOOSHROOM.get(), EntityInfectedMooshroom.createAttributes().build());
        event.put(ModEntities.INFECTED_LLAMA.get(), EntityInfectedLlama.createAttributes().build());
        event.put(ModEntities.INFECTED_POLAR_BEAR.get(), EntityInfectedPolarBear.createAttributes().build());
        event.put(ModEntities.INFECTED_PANDA.get(), EntityInfectedPanda.createAttributes().build());
        event.put(ModEntities.INFECTED_FOX.get(), EntityInfectedFox.createAttributes().build());
        event.put(ModEntities.INFECTED_BEE.get(), EntityInfectedBee.createAttributes().build());
        event.put(ModEntities.ASSIMILATED_HUMAN.get(), EntityAssimilatedHuman.createAttributes().build());
        event.put(ModEntities.ASSIMILATED_COW.get(), EntityAssimilatedCow.createAttributes().build());
        event.put(ModEntities.ASSIMILATED_SHEEP.get(), EntityAssimilatedSheep.createAttributes().build());
        event.put(ModEntities.FERAL_COW.get(), EntityFeralCow.createAttributes().build());
        event.put(ModEntities.FERAL_HUMAN.get(), EntityFeralHuman.createAttributes().build());
        event.put(ModEntities.FERAL_CREEPER.get(), EntityFeralCreeper.createAttributes().build());
        event.put(ModEntities.FERAL_SKELETON.get(), EntityFeralSkeleton.createAttributes().build());
        event.put(ModEntities.FERAL_ZOMBIE.get(), EntityFeralZombie.createAttributes().build());
        event.put(ModEntities.FERAL_SPIDER.get(), EntityFeralSpider.createAttributes().build());
        event.put(ModEntities.FERAL_ENDERMAN.get(), EntityFeralEnderman.createAttributes().build());
        event.put(ModEntities.FERAL_WOLF.get(), EntityFeralWolf.createAttributes().build());
        event.put(ModEntities.FERAL_IRON_GOLEM.get(), EntityFeralIronGolem.createAttributes().build());
        event.put(ModEntities.HIJACKED_CREEPER.get(), EntityHijackedCreeper.createAttributes().build());
        event.put(ModEntities.HIJACKED_SKELETON.get(), EntityHijackedSkeleton.createAttributes().build());
        event.put(ModEntities.HIJACKED_ZOMBIE.get(), EntityHijackedZombie.createAttributes().build());
        event.put(ModEntities.HIJACKED_SPIDER.get(), EntityHijackedSpider.createAttributes().build());
        event.put(ModEntities.HIJACKED_ENDERMAN.get(), EntityHijackedEnderman.createAttributes().build());
        event.put(ModEntities.HIJACKED_WITCH.get(), EntityHijackedWitch.createAttributes().build());
        event.put(ModEntities.HIJACKED_PILLAGER.get(), EntityHijackedPillager.createAttributes().build());
        event.put(ModEntities.HIJACKED_EVOKER.get(), EntityHijackedEvoker.createAttributes().build());
        event.put(ModEntities.HIJACKED_RAVAGER.get(), EntityHijackedRavager.createAttributes().build());
        event.put(ModEntities.INBORN_ALAFIN.get(), EntityAlafin.createAttributes().build());
        event.put(ModEntities.INBORN_OBUS.get(), EntityObus.createAttributes().build());
        event.put(ModEntities.INBORN_NORMAS.get(), EntityNormas.createAttributes().build());
        event.put(ModEntities.INBORN_CANAL.get(), EntityCanal.createAttributes().build());
        event.put(ModEntities.INBORN_GOTHOL.get(), EntityGothol.createAttributes().build());
        event.put(ModEntities.INBORN_KOL.get(), EntityKol.createAttributes().build());
        event.put(ModEntities.INBORN_LESH.get(), EntityLesh.createAttributes().build());
        event.put(ModEntities.INBORN_LODO.get(), EntityLodo.createAttributes().build());
        event.put(ModEntities.INBORN_MOR.get(), EntityMor.createAttributes().build());
        event.put(ModEntities.INBORN_MUDO.get(), EntityMudo.createAttributes().build());
        event.put(ModEntities.INBORN_NUUH.get(), EntityNuuh.createAttributes().build());
        event.put(ModEntities.INBORN_RATHOL.get(), EntityRathol.createAttributes().build());
        event.put(ModEntities.INBORN_VIIN.get(), EntityViin.createAttributes().build());
        event.put(ModEntities.INBORN_ATA.get(), EntityAta.createAttributes().build());
        event.put(ModEntities.INBORN_BUTHOL.get(), EntityButhol.createAttributes().build());
        event.put(ModEntities.CRUDE_SCORCHER.get(), EntityScorcher.createAttributes().build());
        event.put(ModEntities.CRUDE_MINDIM.get(), EntityMindim.createAttributes().build());
        event.put(ModEntities.CRUDE_EGAS.get(), EntityEgas.createAttributes().build());
        event.put(ModEntities.CRUDE_MOVING_FLESH.get(), EntityMovingFlesh.createAttributes().build());
        event.put(ModEntities.CRUDE_WORKER.get(), EntityWorker.createAttributes().build());
        event.put(ModEntities.CRUDE_CRUX_A.get(), EntityCruxA.createAttributes().build());
        event.put(ModEntities.CRUDE_CRUX_B.get(), EntityCruxB.createAttributes().build());
        event.put(ModEntities.CRUDE_DONE.get(), EntityDone.createAttributes().build());
        event.put(ModEntities.CRUDE_HEED.get(), EntityHeed.createAttributes().build());
        event.put(ModEntities.CRUDE_HOST.get(), EntityHost.createAttributes().build());
        event.put(ModEntities.CRUDE_INHOO_M.get(), EntityInhooM.createAttributes().build());
        event.put(ModEntities.CRUDE_INHOO_S.get(), EntityInhooS.createAttributes().build());
        event.put(ModEntities.CRUDE_LEER.get(), EntityLeer.createAttributes().build());
        event.put(ModEntities.CRUDE_LESH.get(), com.subspaceparasite.common.entity.monster.crude.EntityLesh.createAttributes().build());
        event.put(ModEntities.CRUDE_MES.get(), EntityMes.createAttributes().build());
        event.put(ModEntities.CRUDE_QUAC.get(), EntityQuac.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_LONGARMS.get(), EntityLongarms.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_MANDUCATER.get(), EntityManducater.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_REEKER.get(), EntityReeker.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_YELLOWEYE.get(), EntityYelloweye.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_SUMMONER.get(), EntitySummoner.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_BOLSTER.get(), EntityBolster.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_TOZON.get(), EntityTozon.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_ARACHNIDA.get(), EntityArachnida.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_DEVOURER.get(), EntityDevourer.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_VERMIN.get(), EntityVermin.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_VISCERA.get(), EntityViscera.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_BURROWER.get(), EntityBurrower.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_BOMPH.get(), EntityBomph.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_WOLF.get(), EntityPrimitiveWolf.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_BANO.get(), EntityBano.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_CANRA.get(), EntityCanra.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_EMANA.get(), EntityEmana.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_GIM.get(), EntityGim.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_HULL.get(), EntityHull.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_IKI.get(), EntityIki.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_LUM.get(), EntityLum.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_NOGLA.get(), EntityNogla.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_RANRAC.get(), EntityRanrac.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_SHYCO.get(), EntityShyco.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_WYMO.get(), EntityWymo.createAttributes().build());
        event.put(ModEntities.PRIMITIVE_ZAA.get(), EntityZaa.createAttributes().build());
        event.put(ModEntities.ADAPTED_COLONY.get(), EntityColonyAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_CREEPER.get(), EntityCreeperAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_SKELETON.get(), EntitySkeletonAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_SPIDER.get(), EntitySpiderAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_ZOMBIE.get(), EntityZombieAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_ENDERMAN.get(), EntityEndermanAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_BANO.get(), EntityBanoAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_CANRA.get(), EntityCanraAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_EMANA.get(), EntityEmanaAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_GIM.get(), EntityGimAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_HULL.get(), EntityHullAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_IKI.get(), EntityIkiAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_LUM.get(), EntityLumAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_NOGLA.get(), EntityNoglaAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_RANRAC.get(), EntityRanracAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_SHYCO.get(), EntityShycoAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_WYMO.get(), EntityWymoAdapted.createAttributes().build());
        event.put(ModEntities.ADAPTED_ZAA.get(), EntityZaaAdapted.createAttributes().build());
        event.put(ModEntities.PURE_CREEPER.get(), EntityCreeperPure.createAttributes().build());
        event.put(ModEntities.PURE_SKELETON.get(), EntitySkeletonPure.createAttributes().build());
        event.put(ModEntities.PURE_ZOMBIE.get(), EntityZombiePure.createAttributes().build());
        event.put(ModEntities.PURE_SPIDER.get(), EntitySpiderPure.createAttributes().build());
        event.put(ModEntities.PURE_ENDERMAN.get(), EntityEndermanPure.createAttributes().build());
        event.put(ModEntities.PURE_WOLF.get(), EntityWolfPure.createAttributes().build());
        event.put(ModEntities.PURE_FLAM.get(), EntityFlam.createAttributes().build());
        event.put(ModEntities.PURE_FLOG.get(), EntityFlog.createAttributes().build());
        event.put(ModEntities.PURE_OMBOO.get(), EntityOmboo.createAttributes().build());
        event.put(ModEntities.PURE_ALAFHA.get(), EntityAlafha.createAttributes().build());
        event.put(ModEntities.PURE_GANRO.get(), EntityGanro.createAttributes().build());
        event.put(ModEntities.PURE_ESOR.get(), EntityEsor.createAttributes().build());
        event.put(ModEntities.PURE_ELVIA.get(), EntityElvia.createAttributes().build());
        event.put(ModEntities.PURE_ANGED.get(), EntityAnged.createAttributes().build());
        event.put(ModEntities.BECKON_COMMON.get(), EntityBeckonCommon.createAttributes().build());
        event.put(ModEntities.BECKON_UNCOMMON.get(), EntityBeckonUncommon.createAttributes().build());
        event.put(ModEntities.BECKON_RARE.get(), EntityBeckonRare.createAttributes().build());
        event.put(ModEntities.BECKON_EPIC.get(), EntityBeckonEpic.createAttributes().build());
        event.put(ModEntities.BECKON_LEGENDARY.get(), EntityBeckonLegendary.createAttributes().build());
        event.put(ModEntities.DISPATCHER_COMMON.get(), EntityDispatcherCommon.createAttributes().build());
        event.put(ModEntities.DISPATCHER_UNCOMMON.get(), EntityDispatcherUncommon.createAttributes().build());
        event.put(ModEntities.DISPATCHER_RARE.get(), EntityDispatcherRare.createAttributes().build());
        event.put(ModEntities.DISPATCHER_EPIC.get(), EntityDispatcherEpic.createAttributes().build());
        event.put(ModEntities.DISPATCHER_LEGENDARY.get(), EntityDodT.createAttributes().build());
        event.put(ModEntities.ROOTER_COMMON.get(), EntityRooterCommon.createAttributes().build());
        event.put(ModEntities.ROOTER_UNCOMMON.get(), EntityRooterUncommon.createAttributes().build());
        event.put(ModEntities.ROOTER_RARE.get(), EntityRooterRare.createAttributes().build());
        event.put(ModEntities.ROOTER_EPIC.get(), EntityRooterEpic.createAttributes().build());
        event.put(ModEntities.ROOTER_LEGENDARY.get(), EntityLeemB.createAttributes().build());
        event.put(ModEntities.NEXUS_GUARD.get(), EntityNak.createAttributes().build());
        event.put(ModEntities.NEXUS_OVERSEER.get(), EntityUnvo.createAttributes().build());
        event.put(ModEntities.NEXUS_CONSTRUCT.get(), EntityTonro.createAttributes().build());
        event.put(ModEntities.DETERRENT_SENTRY.get(), EntityDeterrentSentry.createAttributes().build());
        event.put(ModEntities.DETERRENT_OUTPOST.get(), EntityDeterrentOutpost.createAttributes().build());
        event.put(ModEntities.DETERRENT_BASTION.get(), EntityDeterrentBastion.createAttributes().build());
        event.put(ModEntities.DETERRENT_VENKROL_SIV.get(), EntityVenkrolSIV.createAttributes().build());
        event.put(ModEntities.PREEMINENT_MARAUDER.get(), EntityPreeminentMarauder.createAttributes().build());
        event.put(ModEntities.PREEMINENT_WARDEN.get(), EntityPreeminentWarden.createAttributes().build());
        event.put(ModEntities.PREEMINENT_SOVEREIGN.get(), EntityPreeminentSovereign.createAttributes().build());
        event.put(ModEntities.ANCIENT_DREADNOUGHT.get(), EntityAncientDreadnought.createAttributes().build());
        event.put(ModEntities.ANCIENT_LEVIATHAN.get(), EntityAncientLeviathan.createAttributes().build());
        event.put(ModEntities.ANCIENT_COLOSSUS.get(), EntityAncientColossus.createAttributes().build());
        event.put(ModEntities.DERIVED_FLY.get(), EntityDerivedFly.createAttributes().build());
        event.put(ModEntities.DERIVED_SWARM.get(), EntityDerivedSwarm.createAttributes().build());
        event.put(ModEntities.DERIVED_CRAWLER.get(), EntityDerivedCrawler.createAttributes().build());
        event.put(ModEntities.DERIVED_LEAPER.get(), EntityDerivedLeaper.createAttributes().build());
        event.put(ModEntities.DERIVED_STALKER.get(), EntityDerivedStalker.createAttributes().build());
        event.put(ModEntities.DERIVED_HEBLU.get(), EntityHeblu.createAttributes().build());
        event.put(ModEntities.DERIVED_KIRIN.get(), EntityKirin.createAttributes().build());
        event.put(ModEntities.ABOMINATION_AMALGAM.get(), EntityAbominationAmalgam.createAttributes().build());
        event.put(ModEntities.ABOMINATION_CHIMERA.get(), EntityAbominationChimera.createAttributes().build());
        event.put(ModEntities.ABOMINATION_HYDRA.get(), EntityAbominationHydra.createAttributes().build());
        event.put(ModEntities.ACID_SPIT.get(), EntityAcidSpit.createAttributes().build());
        event.put(ModEntities.BILE_BOMB.get(), EntityBileBomb.createAttributes().build());
        event.put(ModEntities.SPORE_CLOUD.get(), EntitySporeCloud.createAttributes().build());
        event.put(ModEntities.VIRULENT_SHOT.get(), EntityVirulentShot.createAttributes().build());
        event.put(ModEntities.PARASITE_WEB.get(), EntityParasiteWeb.createAttributes().build());
        event.put(ModEntities.BECKON_BLAST.get(), EntityBeckonBlast.createAttributes().build());
        event.put(ModEntities.NEXUS_BEAM_ENTITY.get(), EntityNexusBeam.createAttributes().build());
        event.put(ModEntities.BUGLIN_ENTITY.get(), EntityBuglin.createAttributes().build());
        event.put(ModEntities.ALVEOLI_WORM.get(), EntityAlveoliWorm.createAttributes().build());
        event.put(ModEntities.PARASITE_LARVA.get(), EntityParasiteLarva.createAttributes().build());
        event.put(ModEntities.VOID_ORB.get(), EntityVoidOrb.createAttributes().build());
        event.put(ModEntities.BOOM_ORB.get(), EntityBoomOrb.createAttributes().build());

        // Note: PROJECTILE_ORB_SCARY, PROJECTILE_ORB_VOID, PROJECTILE_METEOR extend
        // ThrowableProjectile (via EntityOrbBase), not Mob, so they don't need attribute registration.

        LOGGER.debug("Registered attributes for all parasite entity types");
    }

    /**
     * Modify vanilla entity attributes if needed.
     * Can add follow range, knockback resistance, etc. to vanilla
     * entities that parasites interact with.
     */
    @SubscribeEvent
    public static void onEntityAttributeModification(EntityAttributeModificationEvent event) {
        LOGGER.debug("EntityAttributeModificationEvent processed for SubspaceParasite");
    }

    /**
     * Register spawn placement rules for ALL parasite entity types.
     * Uses {@link EntityParasiteBase#checkSpawnRules} for validation.
     * <p>
     * All parasite types use the same spawn placement logic:
     * - Must be on the ground (Heightmap.Types.MOTION_BLOCKING)
     * - Must pass EntityParasiteBase.checkSpawnRules() validation
     */
    @SubscribeEvent
    public static void onSpawnPlacementRegister(SpawnPlacementRegisterEvent event) {
        event.register(ModEntities.INFECTED_HUMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_COW.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_SHEEP.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_CREEPER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_SKELETON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_ZOMBIE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_SPIDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_ENDERMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_PIG.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_CHICKEN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_VILLAGER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_WOLF.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_HORSE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_IRON_GOLEM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_SNOW_GOLEM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_BAT.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_BLAZE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_WITCH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_RAVAGER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_PILLAGER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_EVOKER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_GHAST.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_PHANTOM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_WARDEN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_WITHER_SKELETON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_STRAY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_HUSK.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_DROWNED.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_CAVE_SPIDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_MOOSHROOM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_LLAMA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_POLAR_BEAR.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_PANDA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_FOX.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INFECTED_BEE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ASSIMILATED_HUMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ASSIMILATED_COW.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ASSIMILATED_SHEEP.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_COW.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_HUMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_CREEPER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_SKELETON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_ZOMBIE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_SPIDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_ENDERMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_WOLF.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.FERAL_IRON_GOLEM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_CREEPER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_SKELETON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_ZOMBIE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_SPIDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_ENDERMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_WITCH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_PILLAGER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_EVOKER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.HIJACKED_RAVAGER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_ALAFIN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_OBUS.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_NORMAS.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_CANAL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_GOTHOL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_KOL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_LESH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_LODO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_MOR.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_MUDO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_NUUH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_RATHOL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_VIIN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_ATA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.INBORN_BUTHOL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_SCORCHER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_MINDIM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_EGAS.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_MOVING_FLESH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_WORKER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_CRUX_A.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_CRUX_B.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_DONE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_HEED.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_HOST.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_INHOO_M.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_INHOO_S.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_LEER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_LESH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_MES.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.CRUDE_QUAC.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_LONGARMS.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_MANDUCATER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_REEKER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_YELLOWEYE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_SUMMONER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_BOLSTER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_TOZON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_ARACHNIDA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_DEVOURER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_VERMIN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_VISCERA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_BURROWER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_BOMPH.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_WOLF.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_BANO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_CANRA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_EMANA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_GIM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_HULL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_IKI.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_LUM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_NOGLA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_RANRAC.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_SHYCO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_WYMO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PRIMITIVE_ZAA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_COLONY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_CREEPER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_SKELETON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_SPIDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_ZOMBIE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_ENDERMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_BANO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_CANRA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_EMANA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_GIM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_HULL.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_IKI.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_LUM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_NOGLA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_RANRAC.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_SHYCO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_WYMO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ADAPTED_ZAA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_CREEPER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_SKELETON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_ZOMBIE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_SPIDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_ENDERMAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_WOLF.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_FLAM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_FLOG.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_OMBOO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_ALAFHA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_GANRO.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_ESOR.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_ELVIA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PURE_ANGED.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BECKON_COMMON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BECKON_UNCOMMON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BECKON_RARE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BECKON_EPIC.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BECKON_LEGENDARY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DISPATCHER_COMMON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DISPATCHER_UNCOMMON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DISPATCHER_RARE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DISPATCHER_EPIC.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DISPATCHER_LEGENDARY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ROOTER_COMMON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ROOTER_UNCOMMON.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ROOTER_RARE.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ROOTER_EPIC.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ROOTER_LEGENDARY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.NEXUS_GUARD.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.NEXUS_OVERSEER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.NEXUS_CONSTRUCT.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DETERRENT_SENTRY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DETERRENT_OUTPOST.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DETERRENT_BASTION.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DETERRENT_VENKROL_SIV.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PREEMINENT_MARAUDER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PREEMINENT_WARDEN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PREEMINENT_SOVEREIGN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ANCIENT_DREADNOUGHT.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ANCIENT_LEVIATHAN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ANCIENT_COLOSSUS.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_FLY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_SWARM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_CRAWLER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_LEAPER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_STALKER.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_HEBLU.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.DERIVED_KIRIN.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ABOMINATION_AMALGAM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ABOMINATION_CHIMERA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ABOMINATION_HYDRA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ACID_SPIT.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BILE_BOMB.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.SPORE_CLOUD.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.VIRULENT_SHOT.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PARASITE_WEB.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BECKON_BLAST.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.NEXUS_BEAM_ENTITY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BUGLIN_ENTITY.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.ALVEOLI_WORM.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.PARASITE_LARVA.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.VOID_ORB.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);
        event.register(ModEntities.BOOM_ORB.get(), SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING, EntityParasiteBase::checkSpawnRules, SpawnPlacementRegisterEvent.Operation.OR);

        LOGGER.debug("Registered spawn placements for all parasite entity types");
    }
}
